services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Sincroniza el código fuente
      - /app/node_modules  # Evita conflictos con node_modules
    ports:
      - "5173:5173"  # Mapea el puerto de Vite
    command: npm run dev -- --host  # Ejecuta Vite en modo desarrollo
